### ISSUE TITLE
Does not boot without UEFI

### ISSUE THREAD

**Issue by probonopd** [Nitrux/znx#13]
When UEFI is disabled (in BIOS setup choose "Launch CSM: Always") or on machines without UEFI, media with znx does not boot. Need to set the partition active and also install traditional GRUB2.

**Comment by luis-lavaire** [comment]
Well, that's something that we chose from the beginning. We don't support booting from BIOS; but that was our choice, not a bug.

**Comment by UriHerrera** [comment]
> Well, that's something that we chose from the beginning. We don't support booting from BIOS; but that was our choice, not a bug.

Indeed, this was a choice that we made. EFI and UEFI motherboards have been in the mainstream for some years now. Starting in 2010 when Intel introduced its first-generation Core i3, i5, and i7 and later AMD with its 900 chipset series.

**Comment by probonopd** [comment]
I'm still happily running some machines from 2005ish...

**Comment by luis-lavaire** [comment]
Well, I also have an old laptop from 2006. However, we are looking towards giving support to more modern hardware. And, I reiterate what @UriHerrera wrote: this was a choice we made, not a bug.
