### ISSUE TITLE
Verify ISO and zsync files before deployment

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#15]
znx should be able to verify the integrity of the ISO and zsync files that it uses to deploy and update respectively.

**Comment by UriHerrera** [comment]
Is there any complication on moving to `zsync2` other than it being in development?.

**Comment by luis-lavaire** [comment]
In their Github page, it says that it is not functional now. It would be great if it was working, as it could lead us one step further regarding the security of the update.

**Comment by UriHerrera** [comment]
OK, we can close this until its functional.
