### ISSUE TITLE
Add option to restore ESP files

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#20]
A problem occurs when dual booting an operating system deployed with znx and a Linux distribution using a standard installer, the files in the EFI System Partition that znx creates are overridden in the process. As such, this results in the operating system deployed with znx not be bootable anymore.

Steps to reproduce:

1. Deploy an operating system using `znx`.
2. Shrink the `/data` partition to allocate the secondary operating system.
3. Start the other operating system installer and choose to use `ZNX_BOOT` as the EFI partition.
4. Only the new operating system will boot. Running `sudo update-grub` will not detect other operating systems available.

I tried this with the Ubiquity installer on elementary OS 5.0. Deployed Nitrux, rebooted, used their ISO, shrinked the data partition, started the Ubiquity installer, selected the free space to install elementary OS, choose `ZNX_BOOT` as the ESP, rebooted, and only elementary boots.

I also tried creating a new ESP and point the installer to that new partition but regardless of this Ubiquity writes the files to both ESP partitions overwriting those of `znx`.

From the looks of it is entirely a bug on Ubiquity however we can mitigate this by adding an option that allows znx to restore the `/boot` partition that it creates.

**Comment by luis-lavaire** [comment]
This is, in some way, out of the scope of `znx`. That's because you should let it handle every OS you want to deploy on your machine, instead of creating new partitions.

However, this feature can be easily added (it can even be useful if someone messes-up the ESP someday :sweat_smile:).

**Comment by UriHerrera** [comment]
> This is, in some way, out of the scope of znx. That's because you should let it handle every OS you want to deploy on your machine, instead of creating new partitions.

Yeah, this is 100% a bug of Ubiquity. It shouldn't change files of a partition that it's not being told to touch.

> However, this feature can be easily added (it can even be useful if someone messes-up the ESP someday 😅).
>
> This may have a drawback, though: eOS, in this case, won't be bootable. The best way to "install" it is to deploy it with znx.

If the user creates a second ESP, this won't happen. Ubiquity will write its files to both ESP, but if znx restores its data to the ESP that it created that is it formats and copies its files to `ZNX_BOOT` then the other ESP will still have the EFI files to boot the other OS.

**Comment by UriHerrera** [comment]
I have tried with the Calamares installer too. Calamares does respect` ZNX_BOOT` (doesn't touch it) and also recognizes the user choice of using a separate ESP, so kudos to Calamares.

However, I ran into another issue: I did the same as before however this time only Nitrux would boot and the other system, while installed, does not show up anywhere yet I can access its ESP and its root partition. I used Manjaro this time.

In the GRUB command line of znx I can do `ls` however the partition where the Manjaro root is located only shows up as `No known file system`.

**Comment by luis-lavaire** [comment]
AFAIK, that's because UEFI just supports one ESP.

Which filesystem format did you use for the Manjaro installation?

**Comment by UriHerrera** [comment]
I have four partitions

- /dev/sda1 ZNX_BOOT - fat
- /dev/sda2 ZNX_DATA - btrfs
- /dev/sda3 Manajaro ESP - fat
- /dev/sda4 Manjaro root - ext4

I can see all but the contents of the ext4 partition.

**Comment by luis-lavaire** [comment]
That is because, as of now, `znx` doesn't support the ext4 filesystem. I'll add support for it.

**Comment by luis-lavaire** [comment]
Solved in d722d04: as far as the ESP is not removed, it can be recovered with the `restore-esp` command.
