### ISSUE TITLE
Support resuming a failed deployment.

### ISSUE THREAD

**Issue by luis-lavaire** [Nitrux/znx#23]
As of now, if a deployment of a remote URL fails because of a failure on the network (DHCP configuration changes, network disconnection, etc.), the partially downloaded contents are discarded. Allowing the user to resume a failed deployment would help to reduce bandwidth usage.

A check should be performed at boot time to determine wether the deployment has succeeded or failed.

**Comment by UriHerrera** [comment]
That'd be nice, and axel supports resuming. The issue might be that the server that the user used to download the image from might not.

**Comment by luis-lavaire** [comment]
Yeah, `axel` does support it. However, if the server doesn't support it, the deployment will fail again. That leaves the user in charge of removing the failed deployment. But it will be good if the server supports it, because you won't have to download everything again.

**Comment by UriHerrera** [comment]
Currently, znx supports this feature but as noted if the server doesn't support resuming it won't matter, but that's outside of what znx can resolve.
