### ISSUE TITLE
Enable persistency.

### ISSUE THREAD

**Issue by hezral** [Nitrux/znx#3]
I found this project which is similar and has persistent setup. But i kinda like how znx is doing things. https://github.com/probonopd/SystemImageKit/blob/master/README.md

**Comment by luis-lavaire** [comment]
Hi, @hezral!

You are right: `SystemImageKit` was actually an inspiration for `znx`. We have a side project, that we will soon make public, that will enable persistency. We hope to do it as soon as possible. Please bear in mind that `znx` is still a work-in-progress.

**Comment by luis-lavaire** [comment]
Solved on 815adf016ba32d1b41806feeca02db66d630d0cf.
