### ISSUE TITLE
Development version does not work

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#30]
The current build of znx in the development branch does not work. Every command returns `znx: ERROR: Bad command: wrong number of arguments` except for `help` and `version`.

![Screenshot_20190425_011026](https://user-images.githubusercontent.com/3053525/56713254-f29eeb80-66f6-11e9-8e55-881efaa68d0a.png)
![Screenshot_20190425_011226](https://user-images.githubusercontent.com/3053525/56713358-3265d300-66f7-11e9-9e5a-fb45ab84444e.png)

**Comment by luis-lavaire** [comment]
c47097d solves this issue.
