### ISSUE TITLE
Agregar significado del nombre

### ISSUE THREAD

**Issue by Rodsevich** [Nitrux/znx#31]
Me cuesta un huevo acordarme del nombre del comando, si agregaran en la wiki de dónde sacaron el nombre o algo así que me tire una línea para poder recordarlo, les agradecería

**Comment by luis-lavaire** [comment]
No tiene ningún significado en específico. El nombre fue inspirado en algunos elementos del programa: **z** para el protocolo ZSYNC y **nx** por el nombre de nuestra organización (**N**itru**x**).

**Comment by Rodsevich** [comment]
Gracias
