### ISSUE TITLE
Unused code in build script

### ISSUE THREAD

**Issue by TheAssassin** [Nitrux/znx#33]
https://github.com/Nitrux/znx/blob/b4af21b4923dff4cce04e2e7e510d2831f2d819d/build.sh#L63

**Comment by luis-lavaire** [comment]
Isn't that file needed for the AppImage to work? I read about it [here](https://github.com/AppImage/AppImageKit/wiki/AppImageKit-components).

**Comment by TheAssassin** [comment]
appimagetool embeds a copy of the runtime already. You can pass a custom runtime if you want to, to e.g., build a 64-bit AppImage with the 32-bit appimagetool, or maybe make an ARM AppImage without having to emulate appimagetool for ARM using QEMU. It's not used in your code.

While we're at it, to embed a version in the AppImage, just `export VERSION=...` in your script.

**Comment by TheAssassin** [comment]
Also your embedding of the update information is completely broken. That snippet only ever worked really for type 1. You're using type 2. Just pass `-u '...'` to appimagetool to make it embed that string.

You should refer to https://docs.appimage.org. I'll have to revise the wiki and replace the content there with links to the docs.

**Comment by luis-lavaire** [comment]
Many thanks, @TheAssassin. I'll fix that ASAP.
