### ISSUE TITLE
What is the "compatible ISO"?

### ISSUE THREAD

**Issue by pigmej** [Nitrux/znx#36]
Hey,

In the new docs there is ```download a compatible ISO file and run znx as root.``` what does that exactly mean? What ISOs are compatible? What makes an ISO compatible?

**Comment by luis-lavaire** [comment]
It means that:

- It must be able to boot with a **loopback** file (the original link to the documentation is broken: http://www.supergrubdisk.org/wiki/Loopback.cfg; but here are some links that work: https://www.aioboot.com/en/boot-linux-iso/, https://rmprepusb.blogspot.com/2017/02/make-generic-grub2-boot-menu-using.html).

That's the most very-basic requirement. Note that to enable data persistence across reboots, it should implement a mechanism in the initramfs. An example of how to achieve that is provided [here](https://github.com/Nitrux/nitrux-iso-tool/blob/development/configs/persistence) + [here](https://github.com/Nitrux/nitrux-iso-tool/blob/development/bootstrap.sh#L294-#L295).

And that's pretty much what you require from an ISO to have it working. :grin:
