### ISSUE TITLE
znx update option isn't working

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#44]
Using znx (development branch) to update an ISO image results in the following output:

```
uri@host:~/Downloads$ sudo ./znx_master update /dev/nvme0n1 nx/dev
znx: Updating nitrux/development.
uri@host:~/Downloads$ 
```

It looks like the code is conflicting.

https://github.com/Nitrux/znx/blob/25a0320bc7291ee5db328810ad1aec93fdcca451/appdir/znx#L190-L217

Update:

Commenting the line that does the lookup for the embedded update information in the ISO and leaving only the code that looks for the info file works on a compatible ISO.

It looks like the problem was actually in the ISO file, it didn't have the correct values in the info file that znx reads.

Trying to update would result in this output:

```
znx: Updating nx/dev.
failed on url http://repo.nxos.org:8000/.zsync
could not read control file from URL http://repo.nxos.org:8000/.zsync
znx: Error: Failed to update nx/dev.
```
The archive contains an invalid URL.

In this commit, it's fixed. https://github.com/Nitrux/nitrux-iso-tool/commit/b04789ba42470fdf60be6297789a3df344645979

Update 2:

The latest commit 1b95fd1 in master can update ISO files that only make use of embedded information in the ISO to update the data. 

The latest commit 25a0320 in development can update ISO files that make use of the INFO file in the ISO image. However, it also does this:

```
uri@host:~/Downloads$ sudo ./znx_development update /dev/nvme0n1 nx/dev
znx: Updating nx/dev.
#################### 100.0% 65.5 kBps DONE    

No relevent local data found - I will be downloading the whole file. If that's not what you want, CTRL-C out. You should specify the local file is the old version of the file to download with -i (you might have to decompress it with gzip -d first). Or perhaps you just have no data that helps download the file
downloading from http://repo.nxos.org:8000/nitrux-development-amd64:
-------------------- 0.0% 12.3 kBps         
uri@host:~/Downloads
```

**Comment by luis-lavaire** [comment]
Fixed in d69df77.
