### ISSUE TITLE
Delete remnant folder after removing deployed OS

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#52]
**Describe the bug**
The folder where the operating system was deployed remains in the storage devices even after removing the deployment using znx.

**To Reproduce**
1. Deploy an OS with znx e.g., nx/dev
2. Remove nx/dev using znx
3. dev is deleted but nx remains.

**Expected behavior**
No traces on the storage device.

**Comment by luis-lavaire** [comment]
Fixed in 4294792.
