### ISSUE TITLE
Libraries are not in the correct path

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#53]
**Describe the bug**
These libraries (`libmount` and `libsmartcols`) are not located in the correct path. If the host filesystem where the AppImage is run does not have them or has an outdated version the AppImage will not run, even though they are being included in the AppImage.

**To Reproduce**
1. Download `znx` AppImage.
2. Execute it on a system with util-linux 2.31.
3. `znx` (any branch) doesn't run because one of the libraries might be missing or outdated.
4. Installing the appropriate package with an updated version of the libraries in the host system solves it.

**Expected behavior**
`znx` runs without installing another package.

**Screenshots**
![VirtualBox_Kubuntu_02_09_2019_01_28_08](https://user-images.githubusercontent.com/3053525/64094632-f506f700-cd21-11e9-9eb3-2147f05635d7.png)

![VirtualBox_Kubuntu_02_09_2019_01_45_30](https://user-images.githubusercontent.com/3053525/64095061-5ed3d080-cd23-11e9-8d33-b6c4e5f5379e.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04

**Comment by UriHerrera** [comment]
The easy fix is to edit AppRun and add `/lib` to LD_LIBRARY_PATH:

https://github.com/Nitrux/znx/blob/29f96f96f8d199d4d93b7d855feb2708f715fbfe/appdir/AppRun#L3

**Comment by UriHerrera** [comment]
Commit https://github.com/Nitrux/znx/commit/c0dee5a78149cdc2895dfc3e4f754b96769b16b4 fix this.

![VirtualBox_Kubuntu_02_09_2019_19_04_17](https://user-images.githubusercontent.com/3053525/64136066-7c9d4600-cdb4-11e9-93f9-9a32abdcbbb3.png)

**Comment by luis-lavaire** [comment]
Now `mount` complains:

`mount: /tmp/.mount_znx4swvXE/lib/libmount.so.1: version MOUNT_2.34' not found (required by mount)`

**Comment by luis-lavaire** [comment]
Perhaps this could help: https://github.com/Maverobot/cmake-tools/blob/master/appimage/appimage.sh.

**Comment by UriHerrera** [comment]
I updated the util-linux version that is compiled and bundled in the AppImage to 2.34, which seems to have fixed the problem for Manjaro at least.

![VirtualBox_Nitrux_25_10_2019_18_21_44](https://user-images.githubusercontent.com/3053525/67609813-552f7d80-f754-11e9-8b61-0cb3c75eb542.png)

**Comment by UriHerrera** [comment]
The AppImage also works on Xubuntu 18.04.3.

![VirtualBox_Nitrux_25_10_2019_18_29_12](https://user-images.githubusercontent.com/3053525/67609989-6e84f980-f755-11e9-83dc-d0584c2b835a.png)
