### ISSUE TITLE
Development branch is broken.

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#58]
I've tested the znx development AppImage which includes commits until 7f9740d8c1ba46a069f0284759af8d9ff7e5484d in:

- Xubuntu 18.04.3
- Fedora 30
- Nitrux development

The `init` command generates this message `/tmp/$random/znx: line 107: find_part: command_not_found.` Also, the command does not wipe the drive entirely; the data partition is untouched.

The `deploy` command creates the folders under `/STORE`; however, the ISO image is not downloaded as `IMAGE.0`, but is saved with its original name. Thus, the deployed system does not appear in the boot menu.

The commands `list` and `status` work.

The command `remove` **does not** remove a deployed image.

The commands `reset` and `clean` seemingly don't work either.

The confirmation messages do work. As well as the boot menu displaying recovery entries.

**Comment by luis-lavaire** [comment]
Regarding the commands `remove`, `reset` and `clean`: Do they throw any error message?

**Comment by luis-lavaire** [comment]
The `remove` command wasn't working due to a typo: Instead of calling the `_remove` function (which is associated with the `remove` command), I was calling `_clean`.

**Comment by UriHerrera** [comment]
The commands now work, but the deployed image does not boot. It boots to the GRUB minimal bash-like interface.

**Comment by luis-lavaire** [comment]
I applied the same changes in ab856dc.

**Comment by UriHerrera** [comment]
znx is failing to deploy an image with the error: `SSL error: certificate very failed.`

Znx should probably do: 
1. Try with https and if that fails
2. Use axel's ` --insecure / -k` switch to disable certificate verification.
3. If the image can't be downloaded still, exit.

**Comment by luis-lavaire** [comment]
The use of the `-k` flag may mean a security issue, though. Unless the user trusts the server. Perhaps this should only be enabled explicitly in the command-line.

**Comment by UriHerrera** [comment]
Sure, that's fine with me.

**Comment by luis-lavaire** [comment]
Now it's possible to disable the SSL verification passing the `-k` flag to the `deploy` command; e.g.: `znx deploy -k /dev/sdX im/age https://foo.com/origin.iso`

**Comment by luis-lavaire** [comment]
Solved. The merge to the master branch will be done tonight.
