### ISSUE TITLE
Add a check-update option to znx

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#59]
`znx` doesn't have a way to only check for an update without applying it.

When the user issues the command `znx update`, `znx` will look for the update URL contained in the image, and, if available, apply the update; however, there's no "only check for the update" option.

I suggest a `check-update` option that would only verify if there's a difference between the deployed image and the new image, but without applying the update.

This option can then be used by a GUI to display notifications to the user when a new update for an image is available.

**Comment by luis-lavaire** [comment]
This is a quite interesting feature for GUIs and a daemon checking for updates now and then.

The simpler solution that I can think of is comparing hashes. But, in this case, the presence of an up to date hash in the server should be mandatory (a hash of the image, of course).

We could download the latest hash from the server, calculate the hash of the image locally, and see if those match. If they don't, it means that the image has been modified (updated).

**Comment by luis-lavaire** [comment]
A weak hashing algorithm would be the best option; `md5` would be the best option.

**Comment by luis-lavaire** [comment]
Feature added in 65a5908.

`znx check-update DEVICE IMAGE`.

Developers should now provide both an MD5 hash file and a URL from where such hash can be retrieved. The URL has to be present in the `.INFO` file like this:

```
# The already known UPDATE_URL field.
UPDATE_URL     http://some/where/updates

# === The new field. ===
HASH_URL         http://some/where/hash.md5
```
