### ISSUE TITLE
Add support for aarch64 UEFI (U-boot) boards.

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#61]
For Nitrux to be developed for other CPU architectures, we need our system manager to support different CPU instructions than amd64.

Resources:

- [64-bit Tiano Core UEFI for the Raspberry Pi 3](https://github.com/andreiw/RaspberryPiPkg)
- [U-boot source code from Hardkernel](https://github.com/hardkernel/u-boot)
- [Linux for Amlogic Meson](http://linux-meson.com/doku.php)
     - The ODROID-N2 uses an Amlogic S922X SoC, which is supported.
- [Blobless boot with RockPro64](https://stikonas.eu/wordpress/2019/09/15/blobless-boot-with-rockpro64/)
- [Virtualize UEFI on ARM using QEMU](https://designprincipia.com/virtualize-uefi-on-arm-using-qemu/)

**Comment by luis-lavaire** [comment]
Related to #75.

**Comment by luis-lavaire** [comment]
Support for ARM64 boards is already available in the development branch. Related issue: #75.
