### ISSUE TITLE
Do not publish branches other than master and development

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#67]
Whenever a new branch is created, Travis automatically builds the code in the branch that's fine for debugging, but it clutters the Releases page.

**Comment by luis-lavaire** [comment]
We need to publish those, as they need to be tested before being merged to either `master` or `development`.

**Comment by anupam-git** [comment]
As @luis-lavaire said, the branches are required to be built as it needs to be tested before merging..

I can suggest a solution to not mess up the Releases page, which is to not push to GitHub Releases other than the `master`, `development` and `testing`. For remaining branches make an upload to `transfer.sh`.

Also if you want to skip building for a commit, append `[ci skip]` to your commit message

**Comment by luis-lavaire** [comment]
The `transfer.sh` solution seems very sweet to me. :grin:

**Comment by UriHerrera** [comment]
We'll go with that.
