### ISSUE TITLE
Build product naming

### ISSUE THREAD

**Issue by probonopd** [Nitrux/znx#7]
Please name the build product on `https://github.com/Nitrux/znx/releases` according to the best practices, e.g., `znx-0.0.1-x86_64.AppImage`. This will increase its visibility and make it easier to be included in the AppImageHub central repository of available AppImages. Thank you very much.

**Comment by luis-lavaire** [comment]
@probonopd any advice on how to upload the AppImages to the releases page without deleting them every time I create a new release? I'm using your `uploadtool` script.

**Comment by anupam-git** [comment]
@luis-lavaire Continuous build is supposed to have only one binary (the latest one).

**Comment by anupam-git** [comment]
If you want to create a release, just create a release on github. `uploadtool.sh` will push the build to the respective Release.

**Comment by luis-lavaire** [comment]
Builds generate [files](https://github.com/Nitrux/znx/releases) that are called accordingly to the branch that generated them. A short version of the commit hash is used as the version (`znx version`).

**Comment by UriHerrera** [comment]
@luis-lavaire I'll reopen this issue as it was fully resolved; the uploaded AppImages only have the branch name attached to them.

When we start building AppImages for other architectures like aarch64 it should be appended to the file name.

**Comment by luis-lavaire** [comment]
_*Finally_ solved, as [this](https://travis-ci.org/Nitrux/znx/builds/604567206) Travis build shows.
