### ISSUE TITLE
'-y' flag is not working.

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#70]
**Describe the bug**
`znx` introduced user confirmation for dangerous actions, and it works as long as the input is done manually. Passing the `-y` flag to `znx` does not work.

**To Reproduce**
1. Download `znx` AppImage.
2. Execute a dangerous command such as `znx -y init`.
3. `znx` fails to perform the action with error `znx: Error: Unknown command -y`.

**Expected behavior**
`znx` performs the action requested.

Reference: https://github.com/Nitrux/znx-gui/issues/12

**Comment by luis-lavaire** [comment]
After running:

```bash
ϟ sudo ./znx -y init /dev/sdb
```

The output I got was:

```
[sudo] password for foo: 
Wiping '/dev/sdb'. Please wait.
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk
using fdisk or other utilities.
Setting name!
partNum is 0
Setting name!
partNum is 1
The operation has completed successfully.
mkfs.fat 4.1 (2017-01-24)
btrfs-progs v4.15.1
See http://btrfs.wiki.kernel.org for more information.

Label:              (null)
UUID:               a9a1cfc6-c564-467e-b772-100cbc57612b
Node size:          16384
Sector size:        4096
Filesystem size:    14.37GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP               1.00GiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1    14.37GiB  /dev/sdb2

Successfully initialized '/dev/sdb'.
```

Perhaps you passed the flag in an inappropriate position, e.g.: `znx init -y ...`. Flags are expected to come before anything else.

**Comment by UriHerrera** [comment]
@luis-lavaire You're right; the development branch works, but the master branch doesn't.

**Comment by luis-lavaire** [comment]
I'll create a PR against `master`.

**Comment by luis-lavaire** [comment]
Already solved.
