### ISSUE TITLE
znx fails to remove images.

### ISSUE THREAD

**Issue by unix4you2** [Nitrux/znx#74]
Hi there,

I already added some OS ISOs to a device using `znx`.  When you add the ISO there is no problem.  Check this list with some OS that I deployed using `znx`:

- Deepin/15.11
- ElementaryOS/5.1
- Elive/3.0.6
- FreeBSD/12.1
- Ghost4Linux/0.56
- Haiku/release
- Issabel4/20181002
- KolibriOS/stable
- KubuntuDesktop/19.10
- Nitrux/stable
- OPNSense/19.7
- PuppyPrecise/5.7.1
- REDO/1.0.4
- RedHat/8.1
- TempleOS/stable
- TinyCore/current
- TridentOS-BSD/12
- TrueOS-BSD/disc1
- UbuntuServer/18.04.3
- XubuntuDesktop/18.04.3
- ZorinOS/15.1-Core

**The bug:**
When you try to remove an image that begins with letters there is no problem, look:
```
$ znx remove /dev/sdc TempleOS/stable
znx: Removing TempleOS/stable.
znx: Successfully removed TempleOS/stable.
```
**BUT**, when you try to delete any image that contains hyphens or begins with numbers in its name, you see this error:
```
$ znx remove /dev/sdc TridentOS-BSD/12
znx: Error: Bad image name (must match '^[a-zA-Z0-9_]+/[a-zA-Z0-9_]+$').
```

**To reproduce:**
1. Deploy an image using numbers or minus characters like _TrueOS-BSD/disc1_  or  _REDO/1.0.4_.
2. Try to delete it.

**Expected behavior:**
If `znx` expects the image name to match a regular expression, then the deploy command should prevent the user from deploying such images, to avoid the future error.

**Comment by luis-lavaire** [comment]
Hi, @unix4you2.

It's very probable that you have an outdated release. Please update `znx`. I checked the code and there's no such restriction in the `remove` command; and the `deploy` command does check if the image name matches the regular expression: `^\w+/\w+$` (alphanumeric characters and underscores). This restriction is imposed for the following reasons:

- To prevent abusing parent directories: `../../../image/name`.
- To prevent abusing current directory: `./.`.
- To prevent leading hyphens in filenames (which can be really problematic): `--/--img`.
- Among others.

Simply using an updated version of `znx` will allow you to remove your images. Please fix the names that don't comply with the latest rules by issuing the command: `znx rename [device] [old_name] [new_name]`.

If you still face issues, put them here.

Thanks for using `znx`. :slightly_smiling_face:
