### ISSUE TITLE
Add support for 32-bit UEFI

### ISSUE THREAD

**Issue by starhawk64** [Nitrux/znx#75]
A large number of Chinese copies (most of them rather inexact) of the Intel Compute Stick bundle an Atom or Celeron SoC design (Atom Z3735f, Z8300, Z8350 and Celerons from the N3xxx and N4xxx series are all common) with 2GB, 4GB, or (rarely) 8GB of LPDDR3 and 32GB, 64GB, or (rarely) 128GB of eMMC storage. (eMMC, for the unaware, is a cheaper alternative to a proper SSD. It is typically a single-chip storage solution which interfaces to the system as if it were an SD Card, but its wear-leveling algorithms are considerably better -- although nowhere near as good as SATA SSDs' equivalents -- so that it is suitable for running an OS on, although it's not as fast or as durable as The Real Thing.)

These Chinese computers come in a number of different shapes and sizes, from "stick computers" such as the MeeGoPad T02, to "MiniPCs" such as the Wintel CX-W8 by SunChip (which looks a bit like a Roku box), the MeeGoPad T09 (which is a small rectangle with angled sides and an arced top) and the Vensmile i10 (which looks like the soda-can version of the "trashcan" Mac Pro).

However, they have a lot in common, software-wise. The traditional configuration is either a 32bit copy of Win10 or an older 32bit copy of Win8.1+Bing. If you're "lucky" enough to get one with an activated copy of Windows, you can be reasonably certain that the activation key was created with a keygen rather than anything official. Once in a blue moon the Windows version will be 64bit, but it's pretty rare indeed. Dual-boot scenarios are not uncommon, though, typically involing some version of Ubuntu (usually 16.04 LTS or 18.04 LTS) or a three-eyed four-armed mutant Android that's been badly clobbered into working on _very_ unusual hardware for that OS indeed.

Regardless, they all come with one particularly infuriating unique characteristic. These 64bit systems universally are supplied with a 32bit UEFI.

I would LOVE to try Nitrux on these systems, but currently that is impossible, as without a manual setup procedure (which, although I could *probably* bungle through it, it's needless to say that doing so would be extremely difficult at best!) there is no way to accomplish that -- ZNX does not support 32bit UEFI systems.

There is a publicly-available copy of BOOTIA32.EFI at https://github.com/hirotakaster/baytail-bootia32.efi/blob/master/bootia32.efi -- I have yet to have it *not* work with whatever Rufus puts down (Syslinux, I think?) for booting LiveUSB installs, and it works for GRUB2 full installs later on, if the installer actually completes (most versions of Ubuntu that are branded as such) and doesn't trip over itself when it sees the strange config of a 32bit UEFI on a 64bit system (Mint installer, reliably, or Ubuntu's if there is no active Internet connection available). While I'd like to think that using a simple detect-and-switch sort of setup with ZNX would be fine, I don't actually know -- experimentation is called for.

Nevertheless, adding support for that configuration (32bit UEFI on 64bit computers), even if universal 32bit compatibilitiy -- UEFI or otherwise -- is not in the cards, would be a very nice thing to have, and thus I'm requesting it here.

**Comment by luis-lavaire** [comment]
Hi, @starhawk64.

Adding support for 32-bit UEFIs is trivial (just a matter of generating another GRUB2 image in the proper format, which we already do for x86_64). It will be available in a couple hours.

Apart from that, I like the concept of those little computers. If it's not a problem for you, I'd like to keep track of your experiments with them. :grinning:

**Comment by starhawk64** [comment]
You've got a bit of a backlog, then, my friend, I've built... at least like
five computers with these things.

Got a place I can put a pixdump? :D

**Comment by luis-lavaire** [comment]
New `GRUB2` images were added since https://github.com/Nitrux/znx/commit/36cc81a5d3f71afc7bed344e9307d1ddec86862c.

@starhawk64, get the binary from the [releases page](https://github.com/Nitrux/znx/releases/tag/continuous-development).

**Comment by starhawk64** [comment]
Got it. Also got the dev build of Nitrux -- RN I literally do not have €4
to pay, especially since I'm headed to a relative's house tomorrow for New
Year's Eve.

I won't have an opportunity to test the 32bit UEFI bit till I return
(sorry!) but I think I remember there's a Dell e4310 over there with which
I can play ;) IIRC it already has a blown copy of Win7.

Thx guys :)

**Comment by luis-lavaire** [comment]
You're welcome. Hope it works. I'll leave this issue opened until you can provide feedback about it.

**Comment by starhawk64** [comment]
OK, pulled out a Dell e4310 that's seen better days and booted Nitrux from
a flash drive... interested in first impressions?

**Comment by luis-lavaire** [comment]
Sure! Did it work as expected?

**Comment by starhawk64** [comment]
OK... I'm gonna start off with something that seems off-topic and
unrelated, but is intensely mission-critical but so far almost *completely*
missed by *every* distro.

I live in an apartment complex for people who are either elderly,
handicapped, or disabled. The primary focus of this complex is elderly,
which they define as 63+. If you're physically handicapped, they have two
apartments to choose from. They also have a few apartments for those who
have been able to convince the Social Security Administration that they are
indeed disabled enough to deserve a few pennies from Uncle Sam -- the
average US Disability payment is somewhere around $500/mo. I get a bit over
twice that (lucky bastard that I am) and it is *hard*...

So the other day an elderly lady knocks on my door. She asks if I'm "the TV
guy". I am, and as soon as I can get my shoes on, I walk over to her
apartment nearby, and help her get her stuff properly wired up.

A major part of this is her television. It's an "Element" brand -- and it
has, by a *mile*, the absolute worst interface of any television I've ever
touched. The interface is in fact largely indescribable -- the volume
buttons do one thing, the channel buttons do another, the menu button
itself does a third. The remote control is MIA... and I can't really say
more than that because the button functions seem to be somewhat
context-dependent, and are so convoluted I couldn't really pay attention to
the menu system and which button did what at the same time. Oh -- and all
of the buttons were on the underside of the TV housing -- it had a little
stand to hold it up, but all of this work was done with the TV flat on its
back so that I could see what I was doing to at least a marginal extent.

No wonder this poor lady couldn't figure any of this out! The interface for
this television was designed by an engineer -- and not a particularly good
one. He (we will presume the gender here, solely for the sake of
expediency) did not consider his market, only his job -- to design a menu
system that would control the television as cheaply and simply as possible.
(The specific individual or team in question -- probably individual --
seems, in my estimation, to have been a bit of a sadist, given his
exceptionally awful concoction.)

The LCD television settings menu is the new version of the old "how to
program a VCR" exercise. If a layperson -- especially an elderly layperson
-- cannot reasonably operate his or her purchased equipment and has to rely
on "the family nerd" (or suitable local equivalents thereof), the design of
the equipment is inadequate. Period.

The operation of a Linux distro is all too often a comparable situation.
"Smart people use Linux" is an unwilling slogan imposed on those of us who
choose to avoid the software cartels based in Redmond and Cupertino,
specifically because *those* interfaces, for better or worse, are
reasonably intelligible to the greater non-technical side of the
population. (Arguably, as much as I thoroughly despise That Fruit Company,
*their* interface designs, and the programming efforts underneath and
behind them, are considerably closer to the ideal here, than anything
Microsoft has ever made.)

Some years ago, I began iterating out, in my mind, the requirements for a
Linux distro that would be reasonably comprehensible and operable by
laypeople. What I came up with, ultimately, at least in concept form -- I
am best kept away from code, for the good of humanity! -- was a set of
criteria that will be quite familiar to you:

-- installation of the operating system itself should be as simple and
foolproof as possible.
-- as many common tasks as possible should have preinstalled applications
to handle them.
-- additional applications, where required, should be as painless to
install as the OS.
-- all interfaces should be designed to make sense. If it's not where you'd
ordinarily expect, it's in the wrong place. If it's not labeled the way you
expect, it needs a different name. (Etc.)
-- the entire system should be designed to be as hard to break as possible,
not from an external security standpoint, but from a "hey, what does this
button do?" standpoint...
-- ...but, at the same time, things like putting in a password just to
install software, that's a bit obnoxious and we don't want that.

At the time, I was using Puppy Linux (I soon migrated to a mixture of Mint
and Ubuntu). Your AppImages (which didn't exist yet, I don't believe) were
my bind-mounted SquashFS files. Frugal installs were a thing. I, er, didn't
get much farther, except to come up with an idea for a configurable panel
of a few buttons that could have programs assigned to them, which I called
a "Speed Dial Menu" -- called by a special icon that would toggle its
visibility, it would (ideally) contain the user's most-commonly-used
programs.

I won't pull punches here, in either direction.

I had high hopes for Nitrux... and almost as soon as I hit the desktop,
those hopes were instantly nuked. Big time.

The tray being on top, with a dock at the bottom, will throw a few PC
users, but that's not a major issue. Wireless setup was *mostly* a breeze
-- the time from when I selected a network to being actually connected was
miraculously fast. However -- there is no actual security in visually
obscuring a user's password. The default should be to display the
characters, and the "eye" icon to disable that should be visible even
before characters are entered... and if it's going to be a pictorial icon
(this is one place where Mint gets it right, with a checkbox and a clear
text label explaining what it does) it needs to be considerably more
obvious.

The clock, of all things, is a stumbling block as well. *Some* effort
should be made to personalize the system on a first startup -- hi, how are
you, what is your name and what country do you live in? -- at the absolute
minimum. A 24hr clock outside of military circles -- active, reserve,
retired, vets, etc -- is pretty dang rare here. Yes, in Europe this is
different, but you're not coding just for Europe, now, are you? ;) If you
*absolutely* can't stand a first-run wizard (which you really, really,
*really* should have), at least default to a 12hr clock.

Similarly, the timezone and "advanced" (not in my opinion!) parameters are
*awful* to set up. Scrollbars are a thing, use them. If you want
super-intuitive, have the user put in their actual municipality,
state/province, and country, and look it up online. For the tinfoil hat
crowd, you need a checkbox that says "don't do the default thing to look me
up online" and instead have a fallback that allows one to select from
either a well-known municipality in the proper timezone, or a
GMT/UTC-relative metric. Everything presently scuttled away in "advanced"
should be editable by default and in a plaintext common-sense way. eg, for
setting date format, the user should be able to enter a sample date in
their preferred styles (in my case, expanded/full would be "Wednesday, 1
January 2020", short-form would be "1 Jan 2020"). The current "pick a
country" thing is NUTS.

Your accessibility options are also somewhat limited... to put it
diplomatically. I discovered that my machine (a junker Dell e4310) had lost
its rightmost keyboard column (DEL, ENTER, R_SHIFT, and at least two cursor
keys, up and down, did not work) and was unable to recover because you
failed to anticipate the potential need for an onscreen keyboard. Windows
in general comes with nothing but the most token set of applications. This
has been the case since Win3.x, and I've used nearly every version in that
line -- and, yet, Redmond has you beat here. This is inexcusably shameful.
You need a full suite of proper accessibility tools -- an on-screen
magnifier, pan/zoom desktop functionality, text-to-speech capabilities
(and, ideally, the reverse as well), an onscreen keyboard, etc. Further,
all of these utilities should be in their own menu and it should be clearly
labeled as to its own presence and the effects of the programs within.

I would've tried VMetal -- I wanted to -- but with an inoperative ENTER key
and no onscreen keyboard, I can't even tell you why it didn't work when I
called it. Terminal has no sympathy for those who can't be bothered to
keyboard properly.

Then there's the "applications" menu. Ohhhh boy. NOTHING is clearly
labeled. Getting to the applications *section* is extremely
counterintuitive. I don't know what anything does because nothing is
explained except by the application name, which is generally useless.
Submenus are designated in an extraordinarily unintuitive manner, and you
can't switch between them without either closing the menu entirely and then
reopening it, or hitting the ESC key. This isn't an applications menu. This
isn't a launcher. This is a marginally-operative waste of code that is
borderline USELESS because nobody will EVER make heads or tails of it
except for its original programmer.

You know, I used to hold up the Commodore 64 as the pinnacle of computing
interfaces. You could not use it -- literally -- without at least *some*
idea of what you were doing. The central point of the C64's interface was
that it was worth your time to learn how to compute and how to use this
strange new machine. My philosophy was that people have become lazy and
complacent and that Windows and MacOS and Android and all the others cater
insufferably and incessantly to the broader population's increasing desire
for simple, blissful ignorance.

I was wrong.

Having to learn how to access a disk drive is for nerds. For normal,
everyday people, that idea is very much a textbook application of the
"Ain't nobody got time for that" GIF just waiting to happen.

You have an operating system that COULD be the breatkthrough distro to
bring Linux to the masses. But if you want it to be that, you have to --
for better or worse -- think like the person who understands that pressing
this particular button on the front turns it on and how to use MS Word to
write a resume and formal letter and what an email is and specifically that
and not much more. Think like Granny. Think like the grocery stock clerk,
or dollar-store cashier, or the folks who assemble burgers at the local
fast-food joint. They work hard -- often two jobs, sometimes as many as
three -- and when they get home there's television and homework and bills
and dinner, because if they just go to sleep like they want to, the social
workers and repo dudes will show up and they'll be alone in a tent in the
woods prying cold beans out of a can... at best.

If you get someone like that and you sit them down and they have to ask you
where something is, or how to do 'x' -- or they spend more than ten to
fifteen seconds searching for it -- that is something that needs work.
Period.

UI design is hard. Common sense isn't... and the first is only true if
you're fighting the second ;)

OK, now that I've torn it apart, go fix your shit. I'll be glad to provide
further suggestions later on...

**Comment by starhawk64** [comment]
I have to admit, I'm a bit surprised to have gotten no response at all...
I'm more than happy to engage in dialogue here...

**Comment by UriHerrera** [comment]
@starhawk64 GitHub issues are not intended to be used for long conversational messages like these, but of short ones about the problem described in the OP, however, you're more than welcome to join https://gitter.im/Nitrux/public to chat anytime, or you can also send us another email.

**Comment by luis-lavaire** [comment]
Support for 32-bit UEFI is already available in the development branch. Related issue: #61.
